name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: sudo apt install nasm

    - name: fix
      run: export TERM=xterm

    - name: Make programs
      run: make programs

    - name: Make
      run: make
